name: function_tree
description: A simple library for parsing strings into callable function-trees.
version: 0.5.0
homepage: https://bitbucket.org/ram6ler/function-tree/wiki/Home



environment:
  sdk: '>=2.7.0 <3.0.0'

