name: function_tree
description: A library for parsing and evaluating numerical functions built from strings.
version: 0.1.1
homepage: https://bitbucket.org/ram6ler/function-tree/wiki/Home
author: Richard Ambler <rambler@ibwya.net>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
